# Generated by Django 4.2.29 on 2026-05-20 02:26

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import easy_thumbnails.fields
import phonenumber_field.modelfields
import src.lib.utils.uuid7
import src.users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('public_key', models.CharField(blank=True, editable=False, max_length=256, null=True, unique=True)),
                ('onboarding_status', models.CharField(choices=[('needs_basic_information', 'Needs Basic Information'), ('needs_password', 'Needs Password'), ('needs_email_verification', 'Needs Email Verification'), ('needs_phone_verification', 'Needs Phone Verification'), ('needs_profile_username', 'Needs Profile Username'), ('needs_profile_picture', 'Needs Profile Picture'), ('needs_organization', 'Needs Organization'), ('completed', 'Completed')], db_index=True, default='needs_basic_information', max_length=50)),
                ('profile_picture', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='ProfilePicture')),
                ('picture_url', models.URLField(blank=True, null=True, verbose_name='PictureUrl')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, default=None, max_length=128, null=True, region=None, unique=True)),
                ('institution', models.CharField(blank=True, default='', max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('is_email_verified', models.BooleanField(db_index=True, default=False)),
                ('is_phone_number_verified', models.BooleanField(default=False)),
                ('email_otp_secret', models.CharField(blank=True, default=src.users.models.generate_otp_hash_seed, max_length=128, null=True)),
                ('email_otp_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('email_otp_trials', models.PositiveSmallIntegerField(default=0)),
                ('email_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('email_otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('phone_otp_secret', models.CharField(blank=True, default=src.users.models.generate_otp_hash_seed, max_length=128, null=True)),
                ('phone_otp_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('phone_otp_trials', models.PositiveSmallIntegerField(default=0)),
                ('phone_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('phone_otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('password_reset_otp_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('password_reset_otp_trials', models.PositiveSmallIntegerField(default=0)),
                ('password_reset_otp_expires_at', models.DateTimeField(blank=True, null=True)),
                ('password_reset_otp_locked_until', models.DateTimeField(blank=True, null=True)),
                ('two_factor_otp_secret', models.CharField(blank=True, default=src.users.models.generate_random_secret, max_length=64, null=True)),
                ('two_factor_otp_trials', models.PositiveSmallIntegerField(default=0)),
                ('mfa_is_enabled', models.BooleanField(db_index=True, default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            bases=(src.users.models.OnboardingMixin, src.users.models.UserAuthMixin, models.Model),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='WaitList',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecoveryCode',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('code_hash', models.CharField(db_index=True, max_length=64)),
                ('used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MFATrustedDevice',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('fcm', 'FCM')], default='fcm', max_length=20)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('token', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('last_delivery_status', models.CharField(blank=True, default='', max_length=80)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_trusted_devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MFASession',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=255, unique=True)),
                ('selected_method', models.CharField(blank=True, choices=[('totp', 'TOTP'), ('sms', 'SMS'), ('email', 'Email'), ('webauthn', 'WebAuthn'), ('push', 'Push')], max_length=20, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified', models.BooleanField(db_index=True, default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('request_fingerprint', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MFAMethod',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('totp', 'TOTP'), ('sms', 'SMS'), ('email', 'Email'), ('webauthn', 'WebAuthn'), ('push', 'Push')], db_index=True, max_length=20)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mfa_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MFAChallenge',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('totp', 'TOTP'), ('sms', 'SMS'), ('email', 'Email'), ('webauthn', 'WebAuthn'), ('push', 'Push')], db_index=True, max_length=20)),
                ('challenge_data', models.JSONField(blank=True, default=dict)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='users.mfasession')),
            ],
        ),
        migrations.AddConstraint(
            model_name='recoverycode',
            constraint=models.UniqueConstraint(fields=('user', 'code_hash'), name='unique_recovery_code_per_user'),
        ),
        migrations.AddIndex(
            model_name='mfatrusteddevice',
            index=models.Index(fields=['user', 'is_active'], name='users_mfatr_user_id_832e6f_idx'),
        ),
        migrations.AddConstraint(
            model_name='mfatrusteddevice',
            constraint=models.UniqueConstraint(fields=('provider', 'token'), name='unique_push_device_token_per_provider'),
        ),
        migrations.AddIndex(
            model_name='mfasession',
            index=models.Index(fields=['user', '-created_at'], name='users_mfase_user_id_5ed37d_idx'),
        ),
        migrations.AddIndex(
            model_name='mfasession',
            index=models.Index(fields=['verified', 'expires_at'], name='users_mfase_verifie_203270_idx'),
        ),
        migrations.AddIndex(
            model_name='mfamethod',
            index=models.Index(fields=['user', 'is_active'], name='users_mfame_user_id_6f2007_idx'),
        ),
        migrations.AddConstraint(
            model_name='mfamethod',
            constraint=models.UniqueConstraint(fields=('user', 'type'), name='unique_user_mfa_method_type'),
        ),
        migrations.AddIndex(
            model_name='mfachallenge',
            index=models.Index(fields=['session', 'method'], name='users_mfach_session_3332c9_idx'),
        ),
        migrations.AddIndex(
            model_name='mfachallenge',
            index=models.Index(fields=['expires_at'], name='users_mfach_expires_8d9cf4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_user_email_6f2530_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone_number'], name='users_user_phone_n_7fe504_idx'),
        ),
    ]
