# Generated by Codex on 2026-05-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0001_initial"),
        ("users", "0002_user_institution"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="active_organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_users",
                to="organizations.organization",
            ),
        ),
    ]
