import os


STRIPE_DEBUG = os.getenv("STRIPE_DEBUG", "True") == "True"
STRIPE_TEST_PUBLISHABLE_KEY = os.getenv("STRIPE_TEST_PUBLISHABLE_KEY", "")
STRIPE_TEST_SECRET_KEY = os.getenv("STRIPE_TEST_SECRET_KEY", "")
STRIPE_PROD_PUBLISHABLE_KEY = os.getenv("STRIPE_PROD_PUBLISHABLE_KEY", "")
STRIPE_PROD_SECRET_KEY = os.getenv("STRIPE_PROD_SECRET_KEY", "")
STRIPE_WEBHOOK_KEY = os.getenv("STRIPE_WEBHOOK_KEY")

if STRIPE_DEBUG:
	STRIPE_PUBLISHABLE_KEY = STRIPE_TEST_PUBLISHABLE_KEY
	STRIPE_SECRET_KEY = STRIPE_TEST_SECRET_KEY
else:
	STRIPE_PUBLISHABLE_KEY = STRIPE_PROD_PUBLISHABLE_KEY
	STRIPE_SECRET_KEY = STRIPE_PROD_SECRET_KEY


CHECKOUT_SUCCESS_URL = os.getenv("CHECKOUT_SUCCESS_URL")

ECART_API_ID = os.getenv("ECART_API_ID", "")
PAYSTACK_SECRET = os.getenv("PAYSTACK_SECRET")
