# Generated by Django 4.2.29 on 2026-04-30 11:13

from django.db import migrations, models
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BigLog',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('msg', models.TextField()),
                ('logger', models.CharField(default='', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='LogDBEntry',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('msg', models.CharField(max_length=3000)),
                ('logger', models.CharField(default='', max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
