# Generated by Django 4.2.29 on 2026-04-30 11:13

from django.db import migrations, models
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.CharField(default=src.lib.utils.uuid7.uuid7, editable=False, max_length=255, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
